meta_product_name: "Africarriers Group"
meta_title: "Africarriers Group of Companies - A Giant In Africa"
meta_description: "Relevant description"
meta_image: "cover.png" # should exist in `app/assets/images/`
